services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myturn
    ports:
      - "5432:5432"
    volumes:
      - myturn_pg:/var/lib/postgresql/data

volumes:
  myturn_pg:
