/** Stitch / Material 3 design tokens — official MyTurn mobile foundation */
export const tokens = {
  colors: {
    primary: "#006948",
    primaryContainer: "#00855d",
    onPrimary: "#ffffff",
    onPrimaryContainer: "#f5fff7",
    secondary: "#735c00",
    secondaryContainer: "#fed01b",
    onSecondary: "#ffffff",
    onSecondaryContainer: "#6f5900",
    tertiary: "#17684e",
    tertiaryContainer: "#378166",
    onTertiary: "#ffffff",
    onTertiaryContainer: "#f5fff8",
    background: "#f9f9ff",
    surface: "#f9f9ff",
    surfaceBright: "#f9f9ff",
    surfaceDim: "#d3daea",
    surfaceContainer: "#e7eefe",
    surfaceContainerLow: "#f0f3ff",
    surfaceContainerHigh: "#e2e8f8",
    surfaceContainerHighest: "#dce2f3",
    surfaceContainerLowest: "#ffffff",
    surfaceVariant: "#dce2f3",
    onBackground: "#151c27",
    onSurface: "#151c27",
    onSurfaceVariant: "#3d4a42",
    outline: "#6d7a72",
    outlineVariant: "#bccac0",
    error: "#ba1a1a",
    errorContainer: "#ffdad6",
    onError: "#ffffff",
    primaryFixed: "#85f8c4",
    primaryFixedDim: "#68dba9",
    secondaryFixed: "#ffe083",
    onSecondaryFixed: "#231b00",
    tertiaryFixed: "#a6f2d1",
    onTertiaryFixed: "#002116",
    inversePrimary: "#68dba9",
    gradientStart: "#006948",
    gradientEnd: "#735c00",
  },
  spacing: {
    base: 8,
    gutter: 16,
    mobile: 20,
    section: 32,
    xs: 6,
    sm: 10,
    md: 16,
    lg: 24,
    xl: 32,
  },
  radius: {
    sm: 10,
    md: 16,
    lg: 22,
    xl: 24,
    pill: 999,
  },
  /** Reserved — cards use soft fills only, no elevation shadows. */
  shadow: {
    card: {},
    lift: {},
  },
} as const;

export type Tokens = typeof tokens;
